USE uniboquest;

CREATE TABLE IF NOT EXISTS profiles (
  user_id INT NOT NULL PRIMARY KEY,
  nickname VARCHAR(32) NOT NULL,
  display_name VARCHAR(60) NULL,
  course VARCHAR(80) NULL,
  year_label VARCHAR(20) NULL,
  campus VARCHAR(40) NULL,
  bio VARCHAR(255) NULL,
  pref_events TINYINT(1) NOT NULL DEFAULT 0,
  pref_study  TINYINT(1) NOT NULL DEFAULT 0,
  pref_sport  TINYINT(1) NOT NULL DEFAULT 0,
  pref_social TINYINT(1) NOT NULL DEFAULT 0,
  avatar VARCHAR(30) NULL,
  privacy_public TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_profiles_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
